version: "3.7"
services:
  namenode:
    build: ./namenode
    container_name: namenode
    environment:
      - NODE_ID=namenode
      - PORT_NO=3000
      - STRATEGY=CODED # FULL_FILE | CODED | DEDUP | GEN_DEDUP
      - CACHE_STRATEGY=CODED # SIMPLE | FIFO | TIME | LFU | IMPROVED_LFU | CODED
      - CACHE_SIZE=1000
      - MEASUREMENT_MODE=0
      - BLOCK_SIZE=11
      - BASE_SIZE=10
    volumes:
      - ./data/namenode:/app/data
      - ./db:/app/db
      - ./data_analytics/measurements:/app/measurements
    ports:
      - 3000:3000
  storagenode_1:
    build: ./storagenode
    container_name: storagenode_1
    environment:
      - NODE_ID=storagenode_1
      - PORT_NO=3001
    volumes:
      - ./data/storagenode_1:/app/data
    ports:
      - 3001:3001
  storagenode_2:
    build: ./storagenode
    container_name: storagenode_2
    environment:
      - NODE_ID=storagenode_2
      - PORT_NO=3002
    volumes:
      - ./data/storagenode_2:/app/data
    ports:
      - 3002:3002
  storagenode_3:
    build: ./storagenode
    container_name: storagenode_3
    environment:
      - NODE_ID=storagenode_3
      - PORT_NO=3003
    volumes:
      - ./data/storagenode_3:/app/data
    ports:
      - 3003:3003
  storagenode_4:
    build: ./storagenode
    container_name: storagenode_4
    environment:
      - NODE_ID=storagenode_4
      - PORT_NO=3004
    volumes:
      - ./data/storagenode_4:/app/data
    ports:
      - 3004:3004
