version: "3.7"
services:
  namenode:
    build: ./namenode
    container_name: namenode
    environment:
      - NODE_ID=namenode
      - PORT_NO=3000
    volumes:
      - ./data/namenode:/app/data
      - ./db:/app/db
    ports:
      - 3000:3000
  storagenode_1:
    build: ./storagenode
    container_name: storagenode_1
    environment:
      - NODE_ID=storagenode_1
      - PORT_NO=3001
    volumes:
      - ./data/storagenode_1:/app/data
    ports:
      - 3001:3001
