CACHE_SIZE = 1000

N_FRAGMENTS = CACHE_SIZE // 5 
A_TIER_SIZE = N_FRAGMENTS // 10 
B_TIER_SIZE = N_FRAGMENTS // 8
C_TIER_SIZE = N_FRAGMENTS // 5
D_TIER_SIZE = N_FRAGMENTS // 3
E_TIER_SIZE = N_FRAGMENTS
TOTAL_SIZE = A_TIER_SIZE + B_TIER_SIZE + C_TIER_SIZE + D_TIER_SIZE + E_TIER_SIZE

A_TIER_THRESHOLD = 100 - A_TIER_SIZE / TOTAL_SIZE * 100
B_TIER_THRESHOLD = A_TIER_THRESHOLD - B_TIER_SIZE / TOTAL_SIZE * 100
C_TIER_THRESHOLD = B_TIER_THRESHOLD - C_TIER_SIZE / TOTAL_SIZE * 100
D_TIER_THRESHOLD = C_TIER_THRESHOLD - D_TIER_SIZE / TOTAL_SIZE * 100

print(A_TIER_THRESHOLD)
print(B_TIER_THRESHOLD)
print(C_TIER_THRESHOLD)
print(D_TIER_THRESHOLD)
